{
  "$schema": "https://render.com/schema/v1",
  "services": [
    {
      "type": "web",
      "name": "pomodoro-frontend",
      "env": "static",
      "buildCommand": "npm install && npm run build",
      "staticPublishPath": "./dist",
      "envVars": [
        {
          "key": "VITE_API_URL",
          "sync": false
        }
      ],
      "headers": [
        {
          "path": "/*",
          "name": "X-Frame-Options",
          "value": "sameorigin"
        }
      ],
      "routes": [
        {
          "type": "rewrite",
          "source": "/*",
          "destination": "/index.html"
        }
      ]
    }
  ]
}
